//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge_Sergio_Corrales.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Users
    {
        [DisplayName("Dni")]
        [DisplayFormat(DataFormatString = "s")]
        public int Id_User { get; set; }
        [DisplayName("Nombre")]
        public string Name_User { get; set; }
        [DisplayName("Tipo de Usuario")]
        public string Type_User { get; set; }
        [DisplayName("Contraseña")]
        public string Pass_User { get; set; }
    }
}
